version: "3.8"

services:
  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    command: server standalone

    ports:
      - "8080:8080"

    volumes:
      - ./flows:/app/flows
      - ./PROJET_3:/workspace

    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:h2:mem:public