name: Run script weekly

on:
  push:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python maj.py