name: Run script weekly

on:
  push:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: python -m pip install requests pandas tqdm

      - name: Show installed packages
        run: pip list

      - name: Run script
        run: python maj.py